### PR TITLE
WIP: Try to Improve stream restart on streaming cut

### PR DESCRIPTION
**Pull request by pierre-emmanuelJ**
Restart the stream when the original provider return an http 200 ok because stream normally seams to be permanent (that prevent the final user video player cutting or restarting).

try  to restart 10 times on http 403

this is work but the issue is:
with some video player the video freeze and don't continue.

### CODE REVIEW

**Comment by alexanderadam** [comment]
Is the development here stalled? :fearful:

**Comment by pierre-emmanuelJ** [comment]
I haven't got too much time to develop on it.
And
I'm working on another thing:
the goal is to bufferize or local chunck video to share it between users. and I would like to add an option for real time transcoding for ts -> hls (for chromcast, apple tv...)

**Comment by pierre-emmanuelJ** [comment]
@alexanderadam And another thing I don't know if it's possible because when a stream is cutting I resend a new query. The problem is the player is lost because the new chunck I send doesn't match  to the old chuck family because on the new query it's a new encoding. it's really depend on the iptv provider. I don't know if you understand what I mean?

**Comment by alexanderadam** [comment]
Okay. You probably should close the PR then if you don't plan to develop this branch any further.

**Comment by pierre-emmanuelJ** [comment]
yes thanks

**Pull request closed without merging**
